const express = require('express');
const router = express.Router();
const auth = require('../middleware/authMiddleware');
const upload = require('../middleware/uploadMiddleware');
const folderController = require('../controllers/folderController');
const mediaController = require('../controllers/mediaController');
router.get('/sidebar', auth, folderController.getSidebar);
router.get('/folders/nav', auth, folderController.getAllFoldersForNav);
router.get('/folders/:folderId', auth, folderController.getContent);
router.post('/folders', auth, folderController.createFolder);
router.put('/folders/:id', auth, folderController.updateFolder);
router.post('/folders/:id/delete', auth, folderController.softDeleteFolder);
router.post('/folders/:id/restore', auth, folderController.restoreFolder);
router.post('/folders/:folderId/collaborators', auth, folderController.addCollaborator);
router.delete('/folders/:folderId/collaborators/:collaboratorId', auth, folderController.removeCollaborator);
router.post('/media/upload', auth, upload.array('files'), mediaController.uploadMedia);
router.put('/media/:id', auth, mediaController.updateMedia);
router.put('/media/:id/favorite', auth, mediaController.toggleFavorite);
router.post('/media/:id/delete', auth, mediaController.softDeleteMedia);
router.post('/media/:id/restore', auth, mediaController.restoreMedia);
router.delete('/media/:id/permanent', auth, mediaController.deleteMediaPermanently);

module.exports = router;